GET http://localhost:8080/GamePage/gameMain.html
Cookie: token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyQWNjb3VudCI6IjEiLCJyb2xlIjoiTm9OYW1lIiwidXNlcklkIjozNywic3ViIjoiSnVzdGljZUtuIiwiaXNzIjoiMDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjYiLCJpYXQiOjE1ODkwOTg2NjEsImF1ZCI6InJlc3RhcGl1c2VyIiwiZXhwIjoxNTg5MDk4ODM0LCJuYmYiOjE1ODkwOTg2NjF9.vMCfOoPe95oDT7hYigt45ylIsKQCrWnNMb215xNIbtQ