POST http://localhost:8080/Login
Content-Type: application/x-www-form-urlencoded

account=1&password=1

###
GET http://localhost:8080/GamePage/gameMain.html
###
GET http://localhost:8080/GamePage/Battle